language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - composer self-update
  - composer install

before_script:
  - mysql -e 'create database yii2_test;'

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
